// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ooktILWnxpN-_i8cCHZo8MC9cdC5KeM',
    appId: '1:446485237252:web:5dba8c6efcec6125c16f51',
    messagingSenderId: '446485237252',
    projectId: 'miabe-assistant',
    authDomain: 'miabe-assistant.firebaseapp.com',
    storageBucket: 'miabe-assistant.firebasestorage.app',
    measurementId: 'G-1T6F82YX1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZrIrMyGvCxXMxDms_bI8d8vc6G1iKT4',
    appId: '1:446485237252:android:1261c870ef43ac2bc16f51',
    messagingSenderId: '446485237252',
    projectId: 'miabe-assistant',
    storageBucket: 'miabe-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdIHWiuFV3NZfZkW-fIO_qUc1ho8RZyr0',
    appId: '1:446485237252:ios:a4e81f1e59f2d415c16f51',
    messagingSenderId: '446485237252',
    projectId: 'miabe-assistant',
    storageBucket: 'miabe-assistant.firebasestorage.app',
    androidClientId: '446485237252-i2je9vg1kv4ilvj0l4kgucod850qo3va.apps.googleusercontent.com',
    iosClientId: '446485237252-dbuk8kafdav5a0k8afolp2enhq4a8j62.apps.googleusercontent.com',
    iosBundleId: 'com.miabe.assistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdIHWiuFV3NZfZkW-fIO_qUc1ho8RZyr0',
    appId: '1:446485237252:ios:a4e81f1e59f2d415c16f51',
    messagingSenderId: '446485237252',
    projectId: 'miabe-assistant',
    storageBucket: 'miabe-assistant.firebasestorage.app',
    androidClientId: '446485237252-i2je9vg1kv4ilvj0l4kgucod850qo3va.apps.googleusercontent.com',
    iosClientId: '446485237252-dbuk8kafdav5a0k8afolp2enhq4a8j62.apps.googleusercontent.com',
    iosBundleId: 'com.miabe.assistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ooktILWnxpN-_i8cCHZo8MC9cdC5KeM',
    appId: '1:446485237252:web:2926246646e4dfc5c16f51',
    messagingSenderId: '446485237252',
    projectId: 'miabe-assistant',
    authDomain: 'miabe-assistant.firebaseapp.com',
    storageBucket: 'miabe-assistant.firebasestorage.app',
    measurementId: 'G-98QYZSEGRR',
  );
}
